### ISSUE TITLE
Scaling for minimap

### ISSUE THREAD

**Issue by vytkuklys** [vytkuklys/42_cub3d#2]
*** Issue ***
How to deal with bigger maps and minimap?

*** Details ***
If map is big enough it would cover a big portion of the 3D map.
Currently 5 pixels are given per element in the array.

*** Possible solutions **
Cheap and dirty fix: give a lesser amount of pixels per element depending on size of actual map size.
Optimal: show just part of the map and reveal more based on movement.

**Comment by tblaase** [comment]
was alreday fixed by @vytkuklys 2 days ago
